### ISSUE TITLE
How it will resign after country selection for searched country?

### ISSUE THREAD

**Issue by TheEngineerz** [mustafaibrahim989/MICountryPicker#11]
![screen shot 2016-07-12 at 10 10 47 pm](https://cloud.githubusercontent.com/assets/5149947/16776201/ba8fb976-487d-11e6-9350-684c5143b75a.png)

**Comment by mustafaibrahim989** [comment]
You have to pop/dismiss ViewController explicitly from the delegate method or the closure. See [readme](https://github.com/mustafaibrahim989/MICountryPicker/blob/master/README.md) Example

**Comment by TheEngineerz** [comment]
I am already doing this 

>  picker.didSelectCountryClosure = { name, code in
>             picker.navigationController?.popViewControllerAnimated(true)
>             print(code)
>         }

Which view controller I should dismiss/pop?

**Comment by mustafaibrahim989** [comment]
Fixed in [0.1.9](https://github.com/mustafaibrahim989/MICountryPicker/releases/tag/0.1.9) 🙇 .

Thanks
