### ISSUE TITLE
Wrong selection from filtered result

### ISSUE THREAD

**Issue by abdelrahman-ahmed** [mustafaibrahim989/MICountryPicker#12]
Steps 
1- Type Egypt
2- select first items

Result: selected country  Andora (+376)
Expected:  selected country  Egypt (+20)

**Comment by mustafaibrahim989** [comment]
Which branch or release are you use?

**Comment by abdelrahman-ahmed** [comment]
I installed the latest one using pods.
pod 'MICountryPicker'

**Comment by mustafaibrahim989** [comment]
Can you please give me more details. I can not reproduce this issue

**Comment by iDevelopper** [comment]
Same for me. This is wrong after tapping the search button on the keyboard. Right if not.

**Comment by mustafaibrahim989** [comment]
@iDevelopper Are you using swift-2?

**Comment by iDevelopper** [comment]
Swift 3

**Comment by mustafaibrahim989** [comment]
Fixed 👍. Please update you pods file. Thanks for you contributions @iDevelopper @abdelrahman-ahmed 

Please use this for Swift-3: 
`pod 'MICountryPicker', :git => 'https://github.com/mustafaibrahim989/MICountryPicker.git', :branch => 'master'`

and this for Swift-2:

`pod 'MICountryPicker', :git => 'https://github.com/mustafaibrahim989/MICountryPicker.git', :branch => 'swift-2'`

**Comment by iDevelopper** [comment]
@mustafaibrahim989 , thanks we'll test. :-)
