### ISSUE TITLE
CallingCodes.plist

### ISSUE THREAD

**Issue by MaeseppTarvo** [mustafaibrahim989/MICountryPicker#13]
Hey. Where I can edit the mentioned file? I would like to delete unnecessary countries for me.

**Comment by iDevelopper** [comment]
@mustafaibrahim989 ,Hi, CallingCodes.plist is not installed with CocoaPods.

**Comment by mustafaibrahim989** [comment]
Fixed 👍 
use `pod 'MICountryPicker', :git => 'https://github.com/mustafaibrahim989/MICountryPicker.git', :branch => 'master'` for swift-3
