### ISSUE TITLE
Cannot understand the purpose of popToRootViewcontroller?

### ISSUE THREAD

**Issue by TheEngineerz** [mustafaibrahim989/MICountryPicker#5]
> extension MICountryPicker {
> 
> ```
> override public func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
>     tableView.deselectRowAtIndexPath(indexPath, animated: true)
>     let country: MICountry!
>     if searchController.searchBar.isFirstResponder() {
>         country = filteredList[indexPath.row]
>     } else {
>         country = sections[indexPath.section].countries[indexPath.row]
> 
>     }
>     delegate?.countryPicker(self, didSelectCountryWithName: country.name, code: country.code)
>     didSelectCountryClosure?(country.name, country.code)
>     navigationController?.popToRootViewControllerAnimated(true)
> }
> ```
> 
> }

I think it it should be either pop to previous or dismissviewcontroller depending upon app's behaviour

**Comment by TheEngineerz** [comment]
Sir are you there please resolve this issue Thanks

**Comment by mustafaibrahim989** [comment]
Will be handled from closure or delegate method starting from 0.1.7 👍
