### ISSUE TITLE
Crash when we search country consecutively 2 or 3 times

### ISSUE THREAD

**Issue by TheEngineerz** [mustafaibrahim989/MICountryPicker#9]
when we open the micountrypicker controller and search for any country . go back and then again come on the screen and search again then app crashed

![screen shot 2016-06-29 at 2 27 50 pm](https://cloud.githubusercontent.com/assets/5149947/16447390/cd59562a-3e05-11e6-975c-74194d9750e4.png)

**Comment by mustafaibrahim989** [comment]
This issue fixed in version [0.1.7](https://github.com/mustafaibrahim989/MICountryPicker/releases/tag/0.1.7). use `pod 'MICountryPicker', '0.1.7'`

Thanks
